import type { PerformanceConfig } from '../types/StorageTypes';

import { PERFORMANCE_THRESHOLDS } from './PerformanceThresholds';

/**
 * Shared constants for performance configuration
 * Centralized to eliminate duplication across the codebase
 */

// Connection pool constants
export const CONNECTION_POOL_DEFAULTS = {
  MIN_CONNECTIONS: PERFORMANCE_THRESHOLDS.CONNECTION_POOL_MIN_CONNECTIONS,
  MAX_CONNECTIONS: PERFORMANCE_THRESHOLDS.CONNECTION_POOL_MAX_CONNECTIONS,
  IDLE_TIMEOUT_MS: PERFORMANCE_THRESHOLDS.CONNECTION_POOL_IDLE_TIMEOUT_MS,
  VALIDATION_INTERVAL_MS:
    PERFORMANCE_THRESHOLDS.CONNECTION_POOL_VALIDATION_INTERVAL_MS,
  RETRY_ATTEMPTS: PERFORMANCE_THRESHOLDS.CONNECTION_POOL_RETRY_ATTEMPTS,
  RETRY_BASE_DELAY_MS:
    PERFORMANCE_THRESHOLDS.CONNECTION_POOL_RETRY_BASE_DELAY_MS,
  RETRY_MAX_DELAY_MS: PERFORMANCE_THRESHOLDS.CONNECTION_POOL_RETRY_MAX_DELAY_MS,
  POOL_FULL_DELAY_MS: PERFORMANCE_THRESHOLDS.CONNECTION_POOL_FULL_DELAY_MS,
  MIN_RETRY_DELAY_MS: PERFORMANCE_THRESHOLDS.CONNECTION_POOL_MIN_RETRY_DELAY_MS,
  CLEANUP_CHECK_RATIO:
    PERFORMANCE_THRESHOLDS.CONNECTION_POOL_CLEANUP_CHECK_RATIO,
} as const;

// Query cache constants
export const QUERY_CACHE_DEFAULTS = {
  ENABLED: PERFORMANCE_THRESHOLDS.QUERY_CACHE_ENABLED,
  MAX_SIZE: PERFORMANCE_THRESHOLDS.QUERY_CACHE_MAX_SIZE,
  TTL_MS: PERFORMANCE_THRESHOLDS.QUERY_CACHE_TTL_MS,
} as const;

// Prepared statement cache constants
export const PREPARED_STATEMENT_CACHE_DEFAULTS = {
  ENABLED: PERFORMANCE_THRESHOLDS.PREPARED_STATEMENT_CACHE_ENABLED,
  MAX_SIZE: PERFORMANCE_THRESHOLDS.PREPARED_STATEMENT_CACHE_MAX_SIZE,
} as const;

// Monitoring constants
export const MONITORING_DEFAULTS = {
  ENABLED: PERFORMANCE_THRESHOLDS.MONITORING_ENABLED,
  RETENTION_MS: PERFORMANCE_THRESHOLDS.MONITORING_RETENTION_MS,
  SLOW_QUERY_THRESHOLD_MS:
    PERFORMANCE_THRESHOLDS.MONITORING_SLOW_QUERY_THRESHOLD_MS,
} as const;

// Memory management constants
export const MEMORY_DEFAULTS = {
  MAX_USAGE_BYTES: PERFORMANCE_THRESHOLDS.MEMORY_MAX_USAGE_BYTES,
  CHECK_INTERVAL_MS: PERFORMANCE_THRESHOLDS.MEMORY_CHECK_INTERVAL_MS,
  OPTIMIZATION_ENABLED: true,
} as const;

// Performance thresholds and limits
export const PERFORMANCE_LIMITS = {
  MIN_TIMEOUT_MS: PERFORMANCE_THRESHOLDS.PERFORMANCE_MIN_TIMEOUT_MS,
  MAX_TIMEOUT_MS: PERFORMANCE_THRESHOLDS.PERFORMANCE_MAX_TIMEOUT_MS,
  MIN_CACHE_SIZE: PERFORMANCE_THRESHOLDS.PERFORMANCE_MIN_CACHE_SIZE,
  MAX_CACHE_SIZE: PERFORMANCE_THRESHOLDS.PERFORMANCE_MAX_CACHE_SIZE,
  MIN_CONNECTIONS: PERFORMANCE_THRESHOLDS.PERFORMANCE_MIN_CONNECTIONS,
  MAX_CONNECTIONS: PERFORMANCE_THRESHOLDS.PERFORMANCE_MAX_CONNECTIONS,
  MIN_MEMORY_MB: PERFORMANCE_THRESHOLDS.PERFORMANCE_MIN_MEMORY_MB,
  MAX_MEMORY_MB: PERFORMANCE_THRESHOLDS.PERFORMANCE_MAX_MEMORY_MB,
} as const;

// Time intervals
export const TIME_INTERVALS = {
  ONE_SECOND_MS: PERFORMANCE_THRESHOLDS.TIME_ONE_SECOND_MS,
  ONE_MINUTE_MS: PERFORMANCE_THRESHOLDS.TIME_ONE_MINUTE_MS,
  FIVE_MINUTES_MS: PERFORMANCE_THRESHOLDS.TIME_FIVE_MINUTES_MS,
  TEN_MINUTES_MS: PERFORMANCE_THRESHOLDS.TIME_TEN_MINUTES_MS,
  THIRTY_MINUTES_MS: PERFORMANCE_THRESHOLDS.TIME_THIRTY_MINUTES_MS,
  ONE_HOUR_MS: PERFORMANCE_THRESHOLDS.TIME_ONE_HOUR_MS,
  TWO_HOURS_MS: PERFORMANCE_THRESHOLDS.TIME_TWO_HOURS_MS,
  FOUR_HOURS_MS: PERFORMANCE_THRESHOLDS.TIME_FOUR_HOURS_MS,
} as const;

// Performance profile names
export const PROFILE_NAMES = {
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
  TESTING: 'testing',
  LARGE_REPOSITORY: 'large-repository',
  LOW_MEMORY: 'low-memory',
  CICD: 'cicd',
} as const;

// Re-export thresholds for backward compatibility
export { PERFORMANCE_THRESHOLDS } from './PerformanceThresholds';

// Default performance configuration combining all defaults
export const DEFAULT_PERFORMANCE_CONFIG: PerformanceConfig = {
  connectionPool: {
    minConnections: CONNECTION_POOL_DEFAULTS.MIN_CONNECTIONS,
    maxConnections: CONNECTION_POOL_DEFAULTS.MAX_CONNECTIONS,
    idleTimeoutMs: CONNECTION_POOL_DEFAULTS.IDLE_TIMEOUT_MS,
    validationIntervalMs: CONNECTION_POOL_DEFAULTS.VALIDATION_INTERVAL_MS,
    retryAttempts: CONNECTION_POOL_DEFAULTS.RETRY_ATTEMPTS,
    retryBaseDelayMs: CONNECTION_POOL_DEFAULTS.RETRY_BASE_DELAY_MS,
    retryMaxDelayMs: CONNECTION_POOL_DEFAULTS.RETRY_MAX_DELAY_MS,
  },
  queryCache: {
    enabled: QUERY_CACHE_DEFAULTS.ENABLED,
    maxSize: QUERY_CACHE_DEFAULTS.MAX_SIZE,
    ttlMs: QUERY_CACHE_DEFAULTS.TTL_MS,
  },
  preparedStatementCache: {
    enabled: PREPARED_STATEMENT_CACHE_DEFAULTS.ENABLED,
    maxSize: PREPARED_STATEMENT_CACHE_DEFAULTS.MAX_SIZE,
  },
  monitoring: {
    enabled: MONITORING_DEFAULTS.ENABLED,
    retentionMs: MONITORING_DEFAULTS.RETENTION_MS,
    slowQueryThresholdMs: MONITORING_DEFAULTS.SLOW_QUERY_THRESHOLD_MS,
  },
  memory: {
    maxUsageBytes: MEMORY_DEFAULTS.MAX_USAGE_BYTES,
    checkIntervalMs: MEMORY_DEFAULTS.CHECK_INTERVAL_MS,
    optimizationEnabled: MEMORY_DEFAULTS.OPTIMIZATION_ENABLED,
  },
};
