/**
 * Centralized performance thresholds and constants
 * All hardcoded numbers should be defined here for maintainability
 */

export const PERFORMANCE_THRESHOLDS = {
  // Query performance thresholds
  SLOW_QUERY_MS: 100,
  CRITICAL_QUERY_MS: 1000,
  SLOW_QUERY_BASELINE_MS: 100,

  // Memory thresholds
  MEMORY_GROWTH_MB: 50,
  MEMORY_USAGE_THRESHOLD_BYTES: 100 * 1024 * 1024, // 100MB
  MEMORY_GROWTH_THRESHOLD_MB: 50,
  MEMORY_TREND_THRESHOLD_BYTES: 1024 * 1024, // 1MB

  // Error rate thresholds
  ERROR_RATE_THRESHOLD: 0.05, // 5%
  CRITICAL_ERROR_RATE_THRESHOLD: 0.1, // 10%

  // Connection pool thresholds
  CONNECTION_POOL_UTILIZATION_THRESHOLD: 0.8, // 80%
  CONNECTION_ACQUISITION_THRESHOLD_MS: 50,
  CONNECTION_HEALTH_CRITICAL_RATE: 0.5, // 50%
  CONNECTION_HEALTH_WARNING_RATE: 0.8, // 80%

  // Cache and optimization thresholds
  INDEX_ESTIMATION_RATIO: 0.3, // 30% of database size
  SLOW_QUERY_RATE_THRESHOLD: 0.1, // 10% of queries
  QUERY_IMPROVEMENT_LOW_COST: 10,
  QUERY_IMPROVEMENT_MEDIUM_COST: 50,
  QUERY_IMPROVEMENT_MAX_PERCENTAGE: 100,

  // Resource thresholds
  MAX_SLOW_QUERIES_STORED: 1000,
  QUERY_PLAN_CACHE_TIMEOUT_MS: 300000, // 5 minutes
  RESOURCE_LEAK_THRESHOLD_MS: 300000, // 5 minutes
  MEMORY_SNAPSHOT_MAX_COUNT: 100,
  MEMORY_SNAPSHOT_RECENT_COUNT: 10,
  MEMORY_SNAPSHOT_TREND_COUNT: 5,

  // Cleanup thresholds
  CLEANUP_INTERVAL_RATIO: 0.1, // 10% of retention time
  MEMORY_OPTIMIZATION_SNAPSHOT_RATIO: 0.5, // 50% of max snapshots

  // Display and reporting limits
  TOP_SLOW_QUERIES_LIMIT: 10,
  COMMON_ERRORS_LIMIT: 10,
  QUERY_SUBSTRING_LENGTH: 100,

  // Query optimization scoring
  QUERY_OPTIMIZATION_INDEX_HINT_BONUS: 15,
  QUERY_OPTIMIZATION_GOOD_HINT_BONUS: 10,
  QUERY_OPTIMIZATION_LOW_COST_BONUS: 20,
  QUERY_OPTIMIZATION_MEDIUM_COST_BONUS: 10,

  // Memory management
  MEMORY_CHECK_INTERVAL_MS: 60000, // 1 minute
  MEMORY_MAX_USAGE_BYTES: 100 * 1024 * 1024, // 100MB

  // Connection pool defaults
  CONNECTION_POOL_MIN_CONNECTIONS: 2,
  CONNECTION_POOL_MAX_CONNECTIONS: 10,
  CONNECTION_POOL_IDLE_TIMEOUT_MS: 300000, // 5 minutes
  CONNECTION_POOL_VALIDATION_INTERVAL_MS: 30000, // 30 seconds
  CONNECTION_POOL_RETRY_ATTEMPTS: 3,
  CONNECTION_POOL_RETRY_BASE_DELAY_MS: 1000,
  CONNECTION_POOL_RETRY_MAX_DELAY_MS: 10000,
  CONNECTION_POOL_FULL_DELAY_MS: 50,
  CONNECTION_POOL_MIN_RETRY_DELAY_MS: 1,
  CONNECTION_POOL_CLEANUP_CHECK_RATIO: 2,

  // Query cache defaults
  QUERY_CACHE_ENABLED: true,
  QUERY_CACHE_MAX_SIZE: 1000,
  QUERY_CACHE_TTL_MS: 300000, // 5 minutes

  // Prepared statement cache defaults
  PREPARED_STATEMENT_CACHE_ENABLED: true,
  PREPARED_STATEMENT_CACHE_MAX_SIZE: 100,

  // Monitoring defaults
  MONITORING_ENABLED: true,
  MONITORING_RETENTION_MS: 3600000, // 1 hour
  MONITORING_SLOW_QUERY_THRESHOLD_MS: 100,

  // Performance limits
  PERFORMANCE_MIN_TIMEOUT_MS: 1000,
  PERFORMANCE_MAX_TIMEOUT_MS: 300000,
  PERFORMANCE_MIN_CACHE_SIZE: 10,
  PERFORMANCE_MAX_CACHE_SIZE: 50000,
  PERFORMANCE_MIN_CONNECTIONS: 1,
  PERFORMANCE_MAX_CONNECTIONS: 100,
  PERFORMANCE_MIN_MEMORY_MB: 10,
  PERFORMANCE_MAX_MEMORY_MB: 1024,

  // Time intervals
  TIME_ONE_SECOND_MS: 1000,
  TIME_ONE_MINUTE_MS: 60000,
  TIME_FIVE_MINUTES_MS: 300000,
  TIME_TEN_MINUTES_MS: 600000,
  TIME_THIRTY_MINUTES_MS: 1800000,
  TIME_ONE_HOUR_MS: 3600000,
  TIME_TWO_HOURS_MS: 7200000,
  TIME_FOUR_HOURS_MS: 14400000,

  // Batch operation defaults
  BATCH_OPERATION_CHUNK_SIZE: 1000,
  BATCH_OPERATION_PROGRESS_INTERVAL_MS: 100,

  // Database defaults
  DATABASE_DEFAULT_PAGE_SIZE: 4096,

  // Graceful shutdown defaults
  GRACEFUL_SHUTDOWN_TIMEOUT_MS: 5000,
} as const;
